env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  array-bracket-newline:
    - error
    - consistent
  array-bracket-spacing:
    - error
    - never
  array-element-newline:
    - error
    - consistent
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  block-spacing:
    - error
    - never
  brace-style: error
  camelcase:
    - error
    - properties: never
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  constructor-super: error
  curly:
    - error
    - multi-line
  eol-last: error
  func-call-spacing: error
  generator-star-spacing:
    - error
    - after
  guard-for-in: error
  key-spacing: error
  keyword-spacing: error
  indent:
    - error
    - 2
    - CallExpression:
        arguments: 2
      FunctionDeclaration:
        body: 1
        parameters: 2
      FunctionExpression:
        body: 1
        parameters: 2
      MemberExpression: 2
      ObjectExpression: 1
      SwitchCase: 1
      ignoredNodes:
        - ConditionalExpression
  linebreak-style: error
  max-len:
    - error
    - code: 120
      tabWidth: 2
      ignoreUrls: true
  new-cap: error
  no-array-constructor: error
  no-caller: error
  no-cond-assign: error
  no-extend-native: error
  no-extra-bind: error
  no-irregular-whitespace: error
  no-invalid-this: error
  no-mixed-spaces-and-tabs: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines:
    - error
    - max: 2
  no-new-object: error
  no-new-symbol: error
  no-new-wrappers: error
  no-tabs: error
  no-this-before-super: error
  no-throw-literal: error
  no-trailing-spaces: error
  no-unexpected-multiline: error
  no-unused-vars:
    - error
    - args: none
  no-var: error
  no-with: error
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
  one-var:
    - error
    - var: never
      let: never
      const: never
  operator-linebreak:
    - error
    - after
  padded-blocks:
    - error
    - never
  prefer-const:
    - error
    - destructuring: all
  prefer-promise-reject-errors: error
  prefer-rest-params: error
  prefer-spread: error
  quote-props:
    - error
    - consistent
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  require-jsdoc: off
  rest-spread-spacing: error
  semi: error
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - asyncArrow: always
      anonymous: never
      named: never
  spaced-comment:
    - error
    - always
    - markers: ['/']
  switch-colon-spacing: error
  valid-jsdoc: off
  yield-star-spacing:
    - error
    - after
